version: "3"

services:
  db:
    hostname: db
    container_name: db-stream_handler
    image: ankane/pgvector:latest
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: "no"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: